apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.clientName }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.clientName }}
  namespace: {{ .Values.clientName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.clientName }}
  template:
    metadata:
      labels:
        app: {{ .Values.clientName }}
    spec:
      containers:
        {{- range .Values.modules }}
        - name: {{ .name }}
          image: {{ .image }}
          ports:
            - containerPort: {{ .port }}
          env:
            {{- range $key, $value := .env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
        {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clientName }}-service
  namespace: {{ .Values.clientName }}
spec:
  selector:
    app: {{ .Values.clientName }}
  ports:
    {{- range .Values.modules }}
    - protocol: TCP
      port: {{ .port }}
      targetPort: {{ .port }}
      name: {{ .name }}-port
    {{- end }}
