name: Deploy Specific Client Environment

on:
  push:
    paths:
      - 'C*/**/values.yaml'  # Watches for changes in values.yaml files under any client/env

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Identify Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files: 'C*/**/values.yaml'

      - name: Configure Kubectl
        run: |
          echo "configuring kubeconfig in this need to provide kubeconfig to access the cluster"

      - name: Deploy to Namespace
        run: |
          echo "Need to deploy using helm or kubectl deploy and all the deployments of specific modules and need to provide values file in commnad it self so take the variables from specific file"

      - name: Deployment is confirm
        run: |
          echo "Done!!!!!"
